<?php

/**
 * @file
 * Contains schema_audit.module.
 */

use Drupal\schema_audit\SchemaMetatagManager;

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

function schema_audit_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  $auditor = \Drupal::service('schema_audit.auditor');

  // Search Schema.org for all definitions.
  $data = $auditor->getResponse('All');
  //dpm($data);

  // Search Schema.org for the attributes of the Person class.
  //$data = $auditor->getResponse('Person');
  //dpm($data);

}
